### ISSUE TITLE
MeshLint steals the title text of the INFO box/window

### ISSUE THREAD

**Issue by swtya** [swtya/meshlint-update-to-4.2#1]
During Continuous check, when MeshLint finds something it wants to post it writes to the INFO area title bar.
This then makes it impossible to reconfigure that window for other views.

Offending code is in the announce class around line 369.
area.header_text_set('MeshLint: ' + message)

Printing into the INFO box a message would be preferred behaviour.

**Comment by swtya** [comment]
`Error in bpy.app.handlers.depsgraph_update_post[0]:`
`Traceback (most recent call last):`
`  File "/home/..../.config/blender/4.3/extensions/blender_org/MeshLint/__init__.py", line 289, in global_repeated_check`
`    MeshLintContinuousChecker.check()`
`  File "/home/..../.config/blender/4.3/extensions/blender_org/MeshLint/__init__.py", line 329, in check`
`    cls.announce(None)`
`  File "/home/..../.config/blender/4.3/extensions/blender_org/MeshLint/__init__.py", line 379, in announce`
`    area.header_text_set()`
`TypeError: Area.header_text_set(): required parameter "text" not specified`

Line 379 needs to pass in "None". That will remove the error text and return the title area to a usable state.
